version: '3.8'

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-multi-instance
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - PORT=3000
      - API_SECRET_KEY=${API_SECRET_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SESSIONS_DIR=/app/sessions
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    networks:
      - whatsapp-network
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  whatsapp-network:
    driver: bridge
